version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
      args:
        BUILD_OUTPUT_URL: ${BUILD_OUTPUT_URL}
        BUILD_VERSION_FILE_NAME: ${BUILD_VERSION_FILE_NAME}
    networks:
      cwnet:
        aliases:
          - cw-app
    volumes:
      - web_volume:/cw/web
  dashboard:
    env_file:
        - .env.dashboard
    build:
      context: .
      dockerfile: .docker/dashboard/Dockerfile
      args:
        REPO_PATH: ${DASHBOARD_REPO_PATH}
        REPO_NAME: ${DASHBOARD_REPO_NAME}
    restart: on-failure
    healthcheck:
      test: "exit 0"
    networks:
      cwnet:
        aliases:
          - cw-dashboard
    volumes:
      - data_volume:/cw/data
      - config_volume:/cw/config
      - uploads_volume:/cw/uploads/
      - /var/run/docker.sock:/var/run/docker.sock
  indexer:
    env_file:
        - .env.indexer
    build:
      context: .
      dockerfile: .docker/indexer/Dockerfile
      args:
        BUILD_OUTPUT_URL: ${BUILD_OUTPUT_URL}
        BUILD_VERSION_FILE_NAME: ${BUILD_VERSION_FILE_NAME}
        GOOS: ${GOOS}
        GOARCH: ${GOARCH}
    restart: on-failure
    healthcheck:
      test: "exit 0"
    networks:
      cwnet:
        aliases:
          - cw-indexer
    volumes:
      - data_volume:/cw/data
      - config_volume:/cw/config/:ro
  server:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./.community/nginx/conf/:/etc/nginx/conf.d/:ro
      - certs_www_volume:/var/www/certbot/:ro
      - certs_conf_volume:/etc/nginx/ssl/:ro
      - ./.community/web:/var/www/html/:ro
      - config_volume:/var/www/config/:ro
      - uploads_volume:/var/www/uploads/:ro
    networks:
      cwnet:
        aliases:
          - cw-server
  server-cert:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./.community/nginx_cert/conf/:/etc/nginx/conf.d/:ro
      - certs_www_volume:/var/www/certbot/:ro
      - certs_conf_volume:/etc/nginx/ssl/:ro
    networks:
      cwnet:
        aliases:
          - cw-server-cert
  certbot:
    image: certbot/certbot:latest
    volumes:
      - certs_www_volume:/var/www/certbot/:rw
      - certs_conf_volume:/etc/letsencrypt/:rw
    depends_on:
      - server-cert

volumes:
  web_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/.community/web
  uploads_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/.community/uploads/
  config_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/.community/config
  data_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/.community/data
  certs_www_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/.community/certbot/www/
  certs_conf_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/.community/certbot/conf/

networks:
  cwnet:
    name: cwnet