services:
  server:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./.community/nginx/conf/:/etc/nginx/conf.d/:ro
      - certs_www_volume:/var/www/certbot/:ro
      - certs_conf_volume:/etc/nginx/ssl/:ro
      - web_volume:/var/www/html/:ro
      - config_volume:/var/www/config/:ro
      - uploads_volume:/var/www/uploads/:ro
    networks:
      cwnet:
        aliases:
          - cw-server
  server-cert:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./.community/nginx_cert/conf/:/etc/nginx/conf.d/:ro
      - certs_www_volume:/var/www/certbot/:ro
      - certs_conf_volume:/etc/nginx/ssl/:ro
    networks:
      cwnet:
        aliases:
          - cw-server-cert
  certbot:
    image: certbot/certbot:latest
    volumes:
      - certs_www_volume:/var/www/certbot/:rw
      - certs_conf_volume:/etc/letsencrypt/:rw
    depends_on:
      - server-cert

volumes:
  web_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/.community/web
  uploads_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/.community/uploads/
  config_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/.community/config
  certs_www_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/.community/certbot/www/
  certs_conf_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/.community/certbot/conf/

networks:
  cwnet:
    name: cwnet